<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Pimpinan</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #1f2937;
            line-height: 1.35;
        }
        h1, h2, h3 {
            margin: 0;
        }
        .header {
            border-bottom: 2px solid #0f766e;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }
        .muted {
            color: #4b5563;
        }
        .section {
            margin-top: 14px;
        }
        .grid {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        .grid th, .grid td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: top;
        }
        .grid th {
            background: #ecfeff;
            text-align: left;
            font-weight: 700;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            background: #ccfbf1;
            border: 1px solid #5eead4;
            border-radius: 4px;
            font-size: 11px;
        }
    </style>
</head>
<body>
<div class="header">
    <h2>Laporan Pimpinan Dinas Pertanian</h2>
    <div class="muted">Periode {{ sprintf('%02d/%d', (int) $laporan->bulan, (int) $laporan->tahun) }} ({{ $laporan->tanggal_mulai }} s/d {{ $laporan->tanggal_selesai }})</div>
    <div class="muted">Jenis Laporan: {{ $laporan->jenis_laporan }} | Generated by: {{ $laporan->generated_by }} | Generated at: {{ $laporan->generated_at }}</div>
</div>

<div class="section">
    <h3>Ringkasan Utama</h3>
    <table class="grid">
        <tr>
            <th>Total Produksi</th>
            <th>Total Luas</th>
            <th>Total Petani</th>
            <th>Total Lahan</th>
            <th>Kunjungan Disetujui</th>
        </tr>
        <tr>
            <td>{{ number_format($totals['produksi'], 2, ',', '.') }}</td>
            <td>{{ number_format($totals['luas'], 2, ',', '.') }}</td>
            <td>{{ number_format($totals['petani'], 0, ',', '.') }}</td>
            <td>{{ number_format($totals['lahan'], 0, ',', '.') }}</td>
            <td>{{ number_format($totals['kunjungan_disetujui'], 0, ',', '.') }}</td>
        </tr>
    </table>
</div>

<div class="section">
    <h3>Rekap Kecamatan (Data diproses Admin Kecamatan)</h3>
    <table class="grid">
        <thead>
        <tr>
            <th style="width: 30px;">No</th>
            <th>Kecamatan</th>
            <th>Total Produksi</th>
            <th>Total Luas</th>
            <th>Total Petani</th>
            <th>Total Lahan</th>
        </tr>
        </thead>
        <tbody>
        @forelse($summary as $item)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->nama_kecamatan }}</td>
                <td>{{ number_format((float) $item->total_produksi, 2, ',', '.') }}</td>
                <td>{{ number_format((float) $item->total_luas, 2, ',', '.') }}</td>
                <td>{{ number_format((int) $item->total_petani, 0, ',', '.') }}</td>
                <td>{{ number_format((int) $item->total_lahan, 0, ',', '.') }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="6">Belum ada data rekap kecamatan untuk laporan ini.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>

<div class="section">
    <h3>Sumber Laporan Penyuluh (Status Disetujui)</h3>
    <div class="muted">Maksimal 300 baris terbaru ditampilkan.</div>
    <table class="grid">
        <thead>
        <tr>
            <th style="width: 30px;">No</th>
            <th>Tanggal</th>
            <th>Kecamatan</th>
            <th>Penyuluh</th>
            <th>Petani</th>
            <th>Kondisi/Kesimpulan</th>
        </tr>
        </thead>
        <tbody>
        @forelse($laporanPenyuluh as $item)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->tanggal_kunjungan }}</td>
                <td>{{ $item->nama_kecamatan }}</td>
                <td>{{ $item->nama_penyuluh }}</td>
                <td>{{ $item->nama_petani }}</td>
                <td>
                    <div><span class="badge">Kondisi</span> {{ $item->kondisi_tanaman ?: '-' }}</div>
                    <div><span class="badge">Catatan</span> {{ $item->catatan_umum ?: '-' }}</div>
                    <div><span class="badge">Rekomendasi</span> {{ $item->rekomendasi ?: '-' }}</div>
                    <div><span class="badge">Verifikasi</span> {{ $item->catatan_verifikasi ?: '-' }}</div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="6">Tidak ada laporan kunjungan penyuluh yang disetujui pada periode ini.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>
</body>
</html>
